### ISSUE TITLE
 Avoid running the container in privileged mode

### ISSUE THREAD

**Issue by d6e** [adilinden-oss/docker-rpi-ffmpeg#1]
Using Docker's `--privileged` option is a really  bad idea unless absolutely necessary as it grants the container root  access to the host. Instead, let's limit it to just what it needs.  Docker run has an option for exactly this purpose: `--device=/dev/vchiq`.

**Comment by adilinden** [comment]
Replaced `--privileged` with `--device=/dev/vchiq`.
